[workspace]
members = [
    "intercom-common",
    "intercom-attributes",
    "intercom",
    "intercom-cli",
    "intercom-build",
    "intercom-fmt",
    "basic/client",
    "basic/server",
]
exclude = [ "test" ]
